# Generated by Django 2.1.8 on 2019-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20190716_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='schoolId',
            field=models.CharField(max_length=50),
        ),
    ]
