# Generated by Django 2.1.8 on 2019-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20190716_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='schoolId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
