# Generated by Django 2.1.8 on 2019-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20190716_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='imgOfIdcard',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
