# Generated by Django 2.1.8 on 2019-07-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20190716_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='imgOfIdcard',
        ),
    ]
