# Generated by Django 2.1.8 on 2019-07-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_remove_member_imgofidcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='imgOfIdcard',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
