# Generated by Django 2.1.8 on 2019-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_member_imgofidcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(choices=[(1, '건국대학교'), (2, '서울대학교'), (3, '성신여자대학교'), (4, '숙명여자대학교'), (5, '한국산업기술대학교')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.IntegerField(choices=[(1, '건국대학교'), (2, '서울대학교'), (3, '성신여자대학교'), (4, '숙명여자대학교'), (5, '한국산업기술대학교')], default=1),
        ),
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(to='membership.InterestSchool'),
        ),
    ]
