# Generated by Django 2.1.8 on 2019-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20190731_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestschool',
            name='interest',
        ),
        migrations.AddField(
            model_name='interestschool',
            name='interestin',
            field=models.IntegerField(choices=[(1, '건국대학교'), (2, '서울대학교'), (3, '성신여자대학교'), (4, '숙명여자대학교'), (5, '한국산업기술대학교')], null=True),
        ),
    ]
