# Generated by Django 2.1.8 on 2019-08-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20190731_2223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
