# Generated by Django 2.1.8 on 2019-07-22 09:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
