# Generated by Django 2.2.2 on 2019-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190722_1833'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
