# Generated by Django 2.2.3 on 2019-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='숙명여자대학교')),
                ('coursename', models.CharField(default='강의명', max_length=30)),
                ('prof', models.CharField(default='교수', max_length=30)),
                ('courseyear', models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default='2019')),
                ('coursesemester', models.TextField(choices=[('1학기', '1학기'), ('여름학기', '여름학기'), ('2학기', '2학기'), ('겨울학기', '겨울학기')], default='1학기')),
                ('content', models.TextField(default='강의평을 작성하세요.')),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
            ],
        ),
    ]
