# Generated by Django 2.2.4 on 2019-08-09 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='숙명여자대학교')),
                ('coursename', models.CharField(default='강의명', max_length=30)),
                ('prof', models.CharField(default='교수', max_length=30)),
                ('courseyear', models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default='2019')),
                ('coursesemester', models.TextField(choices=[('1학기', '1학기'), ('여름학기', '여름학기'), ('2학기', '2학기'), ('겨울학기', '겨울학기')], default='1학기')),
                ('content', models.TextField(default='강의평을 작성하세요.')),
                ('assignment', models.TextField(choices=[('없음', '없음'), ('적음', '적음'), ('보통', '보통'), ('헬', '헬')], default='없음')),
                ('test', models.TextField(choices=[('없음', '없음'), ('1회', '1회'), ('2회', '2회'), ('헬', '헬')], default='없음')),
                ('attendence', models.TextField(choices=[('안봄', '안봄'), ('보는듯마는듯', '보는듯마는듯'), ('깐깐', '깐깐')], default='안봄')),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('recommend', models.FloatField(default=0, help_text='(updated on save)')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
