# Generated by Django 2.2.3 on 2019-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.TextField()),
                ('coursename', models.TextField()),
                ('prof', models.TextField()),
                ('courseyear', models.TextField()),
                ('coursesemester', models.TextField()),
                ('content', models.TextField()),
                ('star', models.TextField()),
            ],
        ),
    ]
