# Generated by Django 2.2.3 on 2019-07-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='강의평'),
        ),
        migrations.AlterField(
            model_name='review',
            name='coursename',
            field=models.CharField(default='강의명', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='coursesemester',
            field=models.CharField(default='1학기', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='courseyear',
            field=models.CharField(default='2019', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof',
            field=models.CharField(default='교수', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.TextField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='univ',
            field=models.CharField(default='대학교', max_length=30),
        ),
    ]
