# Generated by Django 2.2.3 on 2019-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='assignment',
            field=models.TextField(choices=[('없음', '없음'), ('적음', '적음'), ('보통', '보통'), ('헬', '헬')], default='없음'),
        ),
        migrations.AddField(
            model_name='review',
            name='attendence',
            field=models.TextField(choices=[('안봄', '안봄'), ('보는듯마는듯', '보는듯마는듯'), ('깐깐', '깐깐')], default='안봄'),
        ),
        migrations.AddField(
            model_name='review',
            name='test',
            field=models.TextField(choices=[('없음', '없음'), ('1회', '1회'), ('2회', '2회'), ('헬', '헬')], default='없음'),
        ),
    ]
