# Generated by Django 2.2.3 on 2019-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190714_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='coursesemester',
            field=models.TextField(choices=[('1학기', '1학기'), ('여름학기', '여름학기'), ('2학기', '2학기'), ('겨울학기', '겨울학기')], default='1학기'),
        ),
        migrations.AlterField(
            model_name='review',
            name='courseyear',
            field=models.IntegerField(choices=[('2018', '2018'), ('2019', '2019')], default='2019'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='univ',
            field=models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='대학교'),
        ),
    ]
