# Generated by Django 2.2.3 on 2019-07-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190714_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='courseyear',
            field=models.TextField(choices=[('2018', '2018'), ('2019', '2019')], default='2019'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.TextField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
