# Generated by Django 2.2.3 on 2019-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190722_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.TextField(choices=[('없음', '없음'), ('적음', '적음'), ('보통', '보통'), ('헬', '헬')], default=5),
        ),
    ]
