# Generated by Django 2.2.3 on 2019-07-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20190714_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='강의평을 작성하세요.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='univ',
            field=models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='숙명여자대학교'),
        ),
    ]
