# Generated by Django 2.2.2 on 2019-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20190722_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.FloatField(default=0, help_text='(updated on save)'),
        ),
    ]
