# Generated by Django 2.2.2 on 2019-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20190714_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='courseyear',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default='2019'),
        ),
    ]
