# Generated by Django 2.2.2 on 2019-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
