# Generated by Django 2.2.4 on 2019-08-09 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='숙명여자대학교')),
                ('schoolyear', models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default='2019')),
                ('schoolsemester', models.TextField(choices=[('1학기', '1학기'), ('여름학기', '여름학기'), ('2학기', '2학기'), ('겨울학기', '겨울학기')], default='1학기')),
                ('content', models.TextField(blank=True, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
