# Generated by Django 2.2.2 on 2019-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreview',
            name='school',
            field=models.CharField(max_length=500),
        ),
    ]
