# Generated by Django 2.2.3 on 2019-08-05 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolreview', '0002_auto_20190804_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolreview',
            name='date',
        ),
        migrations.AddField(
            model_name='schoolreview',
            name='schoolsemester',
            field=models.TextField(choices=[('1학기', '1학기'), ('여름학기', '여름학기'), ('2학기', '2학기'), ('겨울학기', '겨울학기')], default='1학기'),
        ),
        migrations.AddField(
            model_name='schoolreview',
            name='schoolyear',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default='2019'),
        ),
        migrations.AddField(
            model_name='schoolreview',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolreview',
            name='school',
            field=models.TextField(choices=[('숙명여자대학교', '숙명여자대학교'), ('성신여자대학교', '성신여자대학교'), ('서울대학교', '서울대학교'), ('한국산업기술대학교', '한국산업기술대학교'), ('건국대학교', '건국대학교')], default='숙명여자대학교'),
        ),
    ]
